### ISSUE TITLE
Check for reserved character in problem name

### ISSUE THREAD

**Issue by mamun4122** [dipta007/codeforce-code-downloader_gym_non-gym#3]
Windows has some naming convention for file name. Please refer to this link:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions

So, when i try to download the solution for problem [810C](http://codeforces.com/contest/810/problem/C) it gives me error as it has `?` mark in problem name.

![image](https://user-images.githubusercontent.com/9422829/33206404-4e2d67c4-d134-11e7-87d9-7af6bb18e88b.png)

**Comment by dipta007** [comment]
@mamun4122 I hope the issue is fixed
You can check again
and make me sure
TIA
