### ISSUE TITLE
don't run in the ubuntu 16.04

### ISSUE THREAD

**Issue by sbmaruf** [dipta007/codeforce-code-downloader_gym_non-gym#8]
Running on ubuntu 16.04.

error report
--

Traceback (most recent call last):
  File "codeforces-downloader.py", line 51, in <module>
    driver = webdriver.Chrome( GetPathOfChromeDriver() )
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver_linux' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by dipta007** [comment]
Have you downloaded full folder of the code
It needs chromedriver to run
And its included in the github project

**Comment by sbmaruf** [comment]
yes. I have downloaded all everything. The error that is shown is regarding chrome driver. There are some issue with chromedriver lot loading. can you look into it?

**Comment by dipta007** [comment]
Fixed the error, bro.
**Sorry** for the late
